# Generated by Django 3.2.16 on 2023-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(default=5, max_length=256, verbose_name='Строение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=256, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(default=1, max_length=256, verbose_name='Подъезд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='number_phone',
            field=models.CharField(default=1, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=256, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
