# Generated by Django 3.2.16 on 2023-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230909_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(default=10, verbose_name='Объем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.FloatField(default=2, verbose_name='Объем'),
            preserve_default=False,
        ),
    ]
