# Generated by Django 3.2.16 on 2023-10-23 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231001_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=256, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=256, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, max_length=256, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=256, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона пользователя содержит недопустимый символ', regex='^[+*\\w]$')], verbose_name='Номер телефона'),
        ),
    ]
