# Generated by Django 3.2.16 on 2023-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.IntegerField(verbose_name='Объем'),
        ),
    ]
