# Generated by Django 3.2.16 on 2023-11-19 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Номер телефона пользователя содержит недопустимый символ', regex='^[А-Я][а-яё]*$')], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Номер телефона пользователя содержит недопустимый символ', regex='^[А-Я][а-яё]*$')], verbose_name='фамилия'),
        ),
    ]
