# Generated by Django 3.2.16 on 2023-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
