# Generated by Django 3.2.16 on 2023-09-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230913_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='value',
        ),
    ]
