# Generated by Django 3.2.16 on 2023-09-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'район', 'verbose_name_plural': 'районы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
