# Generated by Django 3.2.16 on 2023-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230923_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ImageField(default=0, upload_to='', verbose_name='Статус заказа'),
        ),
    ]
