# Generated by Django 3.2.16 on 2023-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус заказа'),
        ),
    ]
