# Generated by Django 3.2.16 on 2023-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Оформлен', max_length=256, verbose_name='Статус заказа'),
        ),
    ]
